flutter:
  baseUrl: https://www.xxxxx_dev.com/
  code:
    value: 7
    type: string
  otherUrl: https://www.other_url_dev.com/

android:
  applicationId: com.example.dev

ios:

replace_files:
  huawei_json:
    source: assets_1/json.txt
    target: assets/json.txt
  logo:
    source: assets_1/logo.txt
    target: assets/logo.txt